services:
  nginx:
    image: nginx #when image not present locally (no Dockerfile)
    ports:
      - 8000:80
    volumes:
      # use volumes to write in container's folders file
      # - hostPath:containerPath
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  gateway1:
    build: ./backend/gateway  # when have a Dockerfile (image)
    env_file: # provide all env variables
      - ./backend/gateway/.env
    environment:
      - SERVER_NAME=pehla api gateway
    ports:
      - 7001:8000
  
  gateway2:
    build: ./backend/gateway  # when have a Dockerfile (image)
    env_file: # provide all env variables
      - ./backend/gateway/.env
    environment:
      - SERVER_NAME=dusra api gateway
    ports:
      - 7002:8000

  auth-service:
    build: ./backend/services/authService
    env_file:
      - ./backend/services/authService/.env
    ports:
      - 5001:8001

  
  order-service:
    build: ./backend/services/orderService
    env_file:
      - ./backend/services/orderService/.env
    ports:
      - 5002:8001

  
  product-service:
    build: ./backend/services/productService
    env_file:
      - ./backend/services/productService/.env
    ports:
      - 5003:8001



  redis:
    image: redis