events{

}

http{
    upstream backend{
        server gateway1:8000;
        server gateway2:8000;
    }
    server{
        listen 80;
        location /{
            # return 200 "HELLO FROM NGINX";  nginx as a web server

            # as a load balancer:
            proxy_pass http://backend;


        }
    }
}